import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

// SW is generated by vite-plugin-pwa at build time only — skip in dev to avoid
// a 404 MIME-type warning when public/sw.js is absent.
if ("serviceWorker" in navigator && import.meta.env.PROD) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("/sw.js").catch(() => {});
  });
}

createRoot(document.getElementById("root")!).render(<App />);
