import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

const stage = document.getElementById("bg-blur");
if (stage) {
  const plate = `${import.meta.env.BASE_URL}earphoria-redesign/published-home-bg.png`;
  stage.style.backgroundImage = `url("${plate}")`;
}

// SW is generated by vite-plugin-pwa at build time only — skip in dev to avoid
// a 404 MIME-type warning when public/sw.js is absent.
if ("serviceWorker" in navigator && import.meta.env.PROD) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register(import.meta.env.BASE_URL + "sw.js").catch(() => {});
  });
}

createRoot(document.getElementById("root")!).render(<App />);
